import Link from 'next/link';
import { GeometricDynamics } from '@/components/geometric-dynamics';
import { RepresentationSpace } from '@/components/diagrams';
import { LearningLandscape } from '@/components/learning-landscape';

const questions = [
  'How do neural networks learn?',
  'What structure exists inside a neural representation?',
  'How are concepts composed in learned spaces?',
  'How does artificial representation relate to biological cognition?',
  'Can learning dynamics be described using ideas from physics?',
  'What does it mean for an artificial system to understand something?',
  'Can internal mechanisms help us align AI systems?',
];
const noteCategories = ['Physics', 'Mathematics', 'Cognitive Science', 'Artificial Intelligence', 'AI Alignment', 'Papers I’m Reading', 'Research Notes'];

export default function Home() {
  return <main>
    <section className="hero shell" aria-labelledby="hero-title"><div className="hero-meta"><span>UC SAN DIEGO / UNDERGRADUATE</span><span>FIELD NOTES · 001</span></div><div className="hero-grid"><div><p className="eyebrow">PHYSICS <span>×</span> COGNITIVE SCIENCE</p><h1 id="hero-title">Lawson<br/><em>Dong.</em></h1><p className="hero-statement">Understanding intelligence through its internal mechanisms.</p><p className="hero-copy">I am interested in how intelligent systems learn, represent information, and develop internal structure. My current work explores neural representations and learning dynamics through perspectives from cognitive science, physics, and machine learning.</p><a className="text-link" href="#research">Explore the research <span aria-hidden="true">↗</span></a></div><aside className="hero-aside" aria-label="Research directions"><span className="aside-index">FIG. 01 / A WORKING MAP</span><div className="concept-map"><div><small>PHYSICS</small><span>Dynamics</span><span>Learning</span></div><div><small>COGNITIVE SCIENCE</small><span>Representation</span><span>Intelligence</span></div><strong>↓ &nbsp; Understanding AI systems</strong></div><p>Neural representations · Learning dynamics · Cognition · AI alignment</p></aside></div><div className="hero-bottom"><span>SCROLL TO EXPLORE</span><span>↓</span></div></section>

    <section className="section shell research" id="research" aria-labelledby="research-title"><div className="section-top"><span className="section-index">01 / RESEARCH</span><span>SELF-DIRECTED EXPLORATIONS</span></div><div className="section-heading"><h2 id="research-title">Working questions,<br/><em>ongoing experiments.</em></h2><p>Two exploratory projects at the intersection of learned representations, cognition, and the dynamics of training.</p></div>
      <article className="project"><div className="project-head"><span className="project-number">01</span><div><p className="eyebrow">COGNITIVE SCIENCE × AI</p><h3>Representation<br/>Analysis</h3></div><RepresentationSpace/></div><div className="project-body"><p className="project-lead">Exploring the structure of neural representations and their relationship to human cognition.</p><div className="representation-explainer"><div><span className="explainer-label">A SMALL PRIMER / 01</span><h4>What is a representation?</h4><p>In a deep neural network, a representation is an internal vector learned for an input at a hidden layer. The network maps raw data, such as pixels or words, into features that can carry more useful structure for a task. A layer’s activation, an embedding, and a hidden state are all examples.</p><code>h<sup>(0)</sup> = x;&nbsp; h<sup>(ℓ)</sup> = σ(W<sup>(ℓ)</sup>h<sup>(ℓ−1)</sup> + b<sup>(ℓ)</sup>)</code></div><div><span className="explainer-label">A SMALL PRIMER / 02</span><h4>And its space?</h4><p>For a chosen layer, mapping many inputs through the network gives a collection of representation vectors. Their distances, directions, and similarities form the geometry we call a representation space. Each input becomes a point in that space.</p><code>H<sub>ℓ</sub> = {'{'}h<sup>(ℓ)</sup>(x; θ) | x ∈ X{'}'} ⊆ ℝ<sup>dℓ</sup></code><code>f<sub>θ</sub>: X → H<sub>ℓ</sub></code></div></div><div className="project-detail"><span>01.A / MODEL–BRAIN CORRESPONDENCE</span><p>Representational Similarity Analysis across ResNet-18, ResNet-50, and ResNet-152, compared with early visual cortex (EVC) and inferotemporal cortex (IT). Do stages of artificial visual processing correspond to stages of biological vision?</p><a className="text-link subtopic-link" href="https://github.com/Lawson-Dong/representation-alignment-/tree/resnet-human-visual-cortex-rsa" target="_blank" rel="noopener noreferrer" aria-label="View model–brain correspondence on GitHub">View on GitHub <span aria-hidden="true">↗</span></a></div><div className="project-detail"><span>01.B / SEMANTIC COMPOSITION</span><p>Using hybrid concepts in CLIP, such as a dog body with a cat head, to ask how component concepts combine and transform inside a learned representation space.</p><a className="text-link subtopic-link" href="https://github.com/Lawson-Dong/representation-alignment-/tree/clip-semantic-composition" target="_blank" rel="noopener noreferrer" aria-label="View semantic composition on GitHub">View on GitHub <span aria-hidden="true">↗</span></a></div><GeometricDynamics/><Link className="text-link" href="/research/measuring-tools">The measuring tools</Link></div></article>
      <article className="project"><div className="project-head"><span className="project-number">02</span><div><p className="eyebrow">PHYSICS × DEEP LEARNING</p><h3>Learning<br/>Mechanics</h3></div><LearningLandscape/></div><div className="project-body"><p className="project-lead">What if neural-network training can be studied as a discrete dynamical system?</p><div className="project-detail"><span>02.A / TRAJECTORIES</span><p>Exploring optimizer trajectories under SGD, momentum SGD, and Adam, with discrete velocity and acceleration in parameter space.</p></div><div className="project-detail"><span>02.B / TRAINING DYNAMICS</span><p>Investigating learning-rate schedules, overfitting, a proposed “learning Reynolds number,” and experiments with GPT-2 Small, Medium, and Large. These are exploratory questions, not established results.</p></div><a className="text-link" href="https://github.com/Lawson-Dong/learning-mechanics" target="_blank" rel="noopener noreferrer">View research <span aria-hidden="true">↗</span></a></div></article></section>

    <section className="questions-band"><div className="shell questions"><div className="section-top"><span className="section-index">02 / MARGINALIA</span><span>OPEN QUESTIONS</span></div><h2>Questions I Keep<br/><em>Coming Back To</em></h2><ol>{questions.map((q, i) => <li key={q}><span>{String(i + 1).padStart(2, '0')}</span><p>{q}<small aria-hidden="true">↗ still wondering</small></p></li>)}</ol></div></section>

    <section className="section shell notes" id="notes"><div className="section-top"><span className="section-index">03 / DIGITAL GARDEN</span><span>AN EVOLVING INDEX</span></div><div className="section-heading"><h2>Notes, <em>in progress.</em></h2><p>Interactive notes and ideas still taking shape.</p></div><div className="note-list">{noteCategories.map((n, i) => n === 'Mathematics' ? <Link className="note-row note-row-link" href="/mathematics/linear-algebra" key={n}><span>{String(i + 1).padStart(2, '0')}</span><strong>{n}</strong><span className="note-status">Linear Algebra ↗</span></Link> : <div className="note-row" key={n}><span>{String(i + 1).padStart(2, '0')}</span><strong>{n}</strong><span className="note-status">seedling</span></div>)}</div><p className="notes-caption">More notes will grow here over time.</p></section>

    <section className="about-wrap" id="about"><div className="shell about"><div><div className="section-top"><span className="section-index">04 / ABOUT</span></div><h2>Still figuring<br/><em>things out.</em></h2></div><div className="about-copy"><p>I’m an undergraduate at UC San Diego studying Physics and Cognitive Science. I’m interested in understanding intelligent systems from the inside: how learning unfolds, how information becomes represented, and how complex behavior emerges from internal mechanisms.</p><p>My interests currently sit somewhere between physics, cognitive science, machine learning, and AI alignment. Much of my early research has been self-directed and exploratory. I use these projects to formulate questions, learn research methods, and test ideas computationally.</p><a className="text-link" href="mailto:l3dong@ucsd.edu">Get in touch <span aria-hidden="true">↗</span></a></div></div></section>
    <footer className="shell footer"><div><strong>LAWSON DONG</strong><p>Physics + Cognitive Science<br/>UC San Diego</p></div><div className="footer-links"><a href="mailto:l3dong@ucsd.edu">Email ↗</a><a href="https://github.com/Lawson-Dong" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div><Link className="secret" href="/lost" aria-label="A quieter corner of the website" title="lost / 迷子">♪</Link><span className="footer-last">AN UNFINISHED NOTEBOOK · {new Date().getFullYear()}</span></footer>
  </main>;
}
