import { MathTex } from '@/components/math';
import Link from 'next/link';
import { GeometricDynamics } from '@/components/geometric-dynamics';
import { RepresentationSpace } from '@/components/diagrams';
import { LearningLandscape } from '@/components/learning-landscape';

const questions = [
  'How do neural networks learn?',
  'What structure exists inside a neural representation?',
  'How are concepts composed in learned spaces?',
  'How does artificial representation relate to biological cognition?',
  'Can learning dynamics be described using ideas from physics?',
  'What does it mean for an artificial system to understand something?',
  'Can internal mechanisms help us align AI systems?',
];
const noteCategories = ['Physics', 'Mathematics', 'Cognitive Science', 'Artificial Intelligence', 'AI Alignment', 'Papers I’m Reading', 'Research Notes'];

export default function Home() {
  return <main>
    <section className="hero shell" aria-labelledby="hero-title"><div className="hero-meta"><span>UC SAN DIEGO / UNDERGRADUATE</span><span>FIELD NOTES · 001</span></div><div className="hero-grid"><div><p className="eyebrow">PHYSICS <span>×</span> COGNITIVE SCIENCE</p><h1 id="hero-title">Lawson<br/><em>Dong.</em></h1><p className="hero-statement">Understanding intelligence through its internal mechanisms.</p><p className="hero-copy">I am interested in how intelligent systems learn, represent information, and develop internal structure. My current work explores neural representations and learning dynamics through perspectives from cognitive science, physics, and machine learning.</p><a className="text-link" href="#research">Explore the research <span aria-hidden="true">↗</span></a></div><aside className="hero-aside" aria-label="Research directions"><span className="aside-index">FIG. 01 / A WORKING MAP</span><div className="concept-map"><div><small>PHYSICS</small><span>Dynamics</span><span>Learning</span></div><div><small>COGNITIVE SCIENCE</small><span>Representation</span><span>Intelligence</span></div><strong>↓ &nbsp; Understanding AI systems</strong></div><p>Neural representations · Learning dynamics · Cognition · AI alignment</p></aside></div><div className="hero-bottom"><span>SCROLL TO EXPLORE</span><span>↓</span></div></section>

    <section className="section shell research" id="research" aria-labelledby="research-title"><div className="section-top"><span className="section-index">01 / RESEARCH</span><span>SELF-DIRECTED EXPLORATIONS</span></div><div className="section-heading"><h2 id="research-title">Working questions,<br/><em>ongoing experiments.</em></h2><p>Exploratory work on representations and learning dynamics, alongside notes on coding and AI engineering.</p></div>
      <article className="project"><div className="project-head"><span className="project-number">01</span><div><p className="eyebrow">COGNITIVE SCIENCE × AI</p><h3>Representation<br/>Analysis</h3></div><RepresentationSpace/></div><div className="project-body"><p className="project-lead">Exploring the structure of neural representations and their relationship to human cognition.</p><div className="representation-explainer"><div><span className="explainer-label">A SMALL PRIMER / 01</span><h4>What is a representation?</h4><p>In a deep neural network, a representation is an internal vector learned for an input at a hidden layer. The network maps raw data, such as pixels or words, into features that can carry more useful structure for a task. A layer’s activation, an embedding, and a hidden state are all examples.</p><MathTex display tex={String.raw`h^{(0)}=x,\qquad h^{(\ell)}=\sigma\!\left(W^{(\ell)}h^{(\ell-1)}+b^{(\ell)}\right)`} /></div><div><span className="explainer-label">A SMALL PRIMER / 02</span><h4>And its space?</h4><p>For a chosen layer, mapping many inputs through the network gives a collection of representation vectors. Their distances, directions, and similarities form the geometry we call a representation space. Each input becomes a point in that space.</p><MathTex display tex={String.raw`\mathcal H_\ell=\{h^{(\ell)}(x;\theta)\mid x\in\mathcal X\}\subseteq\mathbb R^{d_\ell}`} /><MathTex display tex={String.raw`f_\theta:\mathcal X\to\mathcal H_\ell`} /></div></div><div className="project-detail"><span>01.A / MODEL–BRAIN CORRESPONDENCE</span><p>Representational Similarity Analysis across ResNet-18, ResNet-50, and ResNet-152, compared with early visual cortex (EVC) and inferotemporal cortex (IT). Do stages of artificial visual processing correspond to stages of biological vision?</p><a className="text-link subtopic-link" href="https://github.com/Lawson-Dong/representation-alignment-/tree/resnet-human-visual-cortex-rsa" target="_blank" rel="noopener noreferrer" aria-label="View model–brain correspondence on GitHub">View on GitHub <span aria-hidden="true">↗</span></a></div><div className="project-detail"><span>01.B / SEMANTIC COMPOSITION</span><p>Using hybrid concepts in CLIP, such as a dog body with a cat head, to ask how component concepts combine and transform inside a learned representation space.</p><a className="text-link subtopic-link" href="https://github.com/Lawson-Dong/representation-alignment-/tree/clip-semantic-composition" target="_blank" rel="noopener noreferrer" aria-label="View semantic composition on GitHub">View on GitHub <span aria-hidden="true">↗</span></a></div><GeometricDynamics/></div></article>
      <article className="project"><div className="project-head"><span className="project-number">02</span><div><p className="eyebrow">PHYSICS × DEEP LEARNING</p><h3>Learning<br/>Mechanics</h3></div><LearningLandscape/></div><div className="project-body"><p className="project-lead">What if neural-network training can be studied as a discrete dynamical system?</p><div className="project-detail"><span>02.A / TRAJECTORIES</span><p>Exploring optimizer trajectories under SGD, momentum SGD, and Adam, with discrete velocity and acceleration in parameter space.</p></div><div className="project-detail"><span>02.B / TRAINING DYNAMICS</span><p>Investigating learning-rate schedules, overfitting, a proposed “learning Reynolds number,” and experiments with GPT-2 Small, Medium, and Large. These are exploratory questions, not established results.</p></div><a className="text-link" href="https://github.com/Lawson-Dong/learning-mechanics" target="_blank" rel="noopener noreferrer">View research <span aria-hidden="true">↗</span></a></div></article>
      <article className="project" id="coding-ai-engineering" style={{scrollMarginTop: '95px'}} aria-labelledby="coding-title">
        <div className="project-head"><span className="project-number">03</span><div><p className="eyebrow">PYTHON × AI</p><h3 id="coding-title">Coding and<br/>AI Engineering</h3></div></div>
        <div className="project-body"><p className="project-lead">Learning the language behind the experiments: Python fundamentals, object behavior, and the foundations of AI engineering.</p><p style={{color: 'var(--muted)', lineHeight: 1.8, gridColumn: '1 / -1'}}>COGS 18 / Python field notes. Small examples from my first steps in programming.</p>
        <details className="project-detail coding-note" open><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>STRINGS / QUOTES & ESCAPES</summary><p>Outer quotes delimit a string; they are not part of its value. Switch quote styles or escape an inner quote.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"message = \"what's your name?\"\nother = 'what\\'s your name?'\nprint(message)  # what's your name?\nquoted = \"'hello'\"  # inner quotes are content"}</code></pre></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>NUMBERS / DIVISION & MIXED TYPES</summary><p>For built-in int and float values, / returns a float. Mixed int–float arithmetic produces a float. // floors the quotient; two integer operands give an integer result.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"5 / 5          # 1.0\n123 + 5 / 5    # 124.0\n123 + 5 // 5   # 124\n10 + 10.1      # 20.1\n-7 // 2        # -4 (floor, not truncation)"}</code></pre><p>Floating-point numbers have finite precision; very large integers may lose precision when converted to float.</p></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>COMPARISON / ASSIGNMENT & EQUALITY</summary><p>Use = to bind a name and == to compare values. Python has no === operator.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"x = 4\nx == 4             # True\nx != 4             # False\n(6 < 20) and (4 == 4)  # True\n# Other comparisons: <, >, <=, >= "}</code></pre></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>LOGIC / AND, OR & NOT</summary><p>With boolean operands, and requires both to be true; or requires at least one. not negates one expression and goes before it.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"True and False   # False\nTrue or False    # True\nnot True         # False\nnot False        # True\nTrue != False    # True\n# True not False is invalid syntax"}</code></pre></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>OBJECTS / IDENTITY & SHARED REFERENCES</summary><p>Assignment binds a name to an object; it does not copy that object. == compares values; is compares object identity. Two names can refer to the same mutable list.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"a = [1, 2, 3]\nb = a\nc = [1, 2, 3]\na is b    # True\nc is a    # False\nc == a    # True\nb.append(4)\nprint(a)  # [1, 2, 3, 4]\n# id(a) == id(b); id(a) != id(c)"}</code></pre><p>Rebinding <code>b</code> to another object does not change <code>a</code>. Use <code>is</code> for identity checks such as <code>x is None</code>, and <code>==</code> for numeric or string equality. Equal numbers or strings may be reused internally; do not rely on that identity.</p></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>STRINGS / MEMBERSHIP & EMPTY STRINGS</summary><p>For strings, in tests for a contiguous substring. A space has length 1; the empty string has length 0 and is a substring of every string.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"x = 'I love COGS18!'\n'l' in x       # True\n'COGS' in x    # True\n'CSOG' in x    # False\n' ' in x       # True\n'' in x        # True\nlen(' ')       # 1\nlen('')        # 0\n'' in ''       # True"}</code></pre></details>
        </div>
      </article>
</section>

    <section className="questions-band"><div className="shell questions"><div className="section-top"><span className="section-index">02 / MARGINALIA</span><span>OPEN QUESTIONS</span></div><h2>Questions I Keep<br/><em>Coming Back To</em></h2><ol>{questions.map((q, i) => <li key={q}><span>{String(i + 1).padStart(2, '0')}</span><p>{q}<small aria-hidden="true">↗ still wondering</small></p></li>)}</ol></div></section>

    <section className="section shell notes" id="notes"><div className="section-top"><span className="section-index">03 / DIGITAL GARDEN</span><span>AN EVOLVING INDEX</span></div><div className="section-heading"><h2>Notes, <em>in progress.</em></h2><p>Interactive notes and ideas still taking shape.</p></div><div className="note-list">{noteCategories.map((n, i) => n === 'Mathematics' ? <Link className="note-row note-row-link" href="/mathematics/linear-algebra" key={n}><span>{String(i + 1).padStart(2, '0')}</span><strong>{n}</strong><span className="note-status">Linear Algebra ↗</span></Link> : <div className="note-row" key={n}><span>{String(i + 1).padStart(2, '0')}</span><strong>{n}</strong><span className="note-status">seedling</span></div>)}</div><p className="notes-caption">More notes will grow here over time.</p></section>

    <section className="about-wrap" id="about"><div className="shell about"><div><div className="section-top"><span className="section-index">04 / ABOUT</span></div><h2>Still figuring<br/><em>things out.</em></h2></div><div className="about-copy"><p>I’m an undergraduate at UC San Diego studying Physics and Cognitive Science. I’m interested in understanding intelligent systems from the inside: how learning unfolds, how information becomes represented, and how complex behavior emerges from internal mechanisms.</p><p>My interests currently sit somewhere between physics, cognitive science, machine learning, and AI alignment. Much of my early research has been self-directed and exploratory. I use these projects to formulate questions, learn research methods, and test ideas computationally.</p><a className="text-link" href="mailto:l3dong@ucsd.edu">Get in touch <span aria-hidden="true">↗</span></a></div></div></section>
    <footer className="shell footer"><div><strong>LAWSON DONG</strong><p>Physics + Cognitive Science<br/>UC San Diego</p></div><div className="footer-links"><a href="mailto:l3dong@ucsd.edu">Email ↗</a><a href="https://github.com/Lawson-Dong" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div><Link className="secret" href="/lost" aria-label="A quieter corner of the website" title="lost / 迷子">♪</Link><span className="footer-last">AN UNFINISHED NOTEBOOK · {new Date().getFullYear()}</span></footer>
  </main>;
}
