'use client';
import {useRef,useState} from 'react';
import ReactMarkdown from 'react-markdown';
const limit=12000;
export function MessageEditor(){
 const [body,setBody]=useState('');const [title,setTitle]=useState('');const [name,setName]=useState('');const [trap,setTrap]=useState('');const [preview,setPreview]=useState(false);const [sending,setSending]=useState(false);const [status,setStatus]=useState<{type:'error'|'success';text:string}|null>(null);const editor=useRef<HTMLTextAreaElement>(null);
 function insert(before:string,after=''){const el=editor.current;if(!el||preview)return;const start=el.selectionStart,end=el.selectionEnd;const selected=body.slice(start,end)||'text';const next=body.slice(0,start)+before+selected+after+body.slice(end);if(next.length>limit)return;setBody(next);requestAnimationFrame(()=>{el.focus();el.setSelectionRange(start+before.length,start+before.length+selected.length);});}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(sending)return;setSending(true);setStatus(null);try{const res=await fetch('/api/messages',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,body,name,website:trap})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Your message could not be sent. Please try again.');setStatus({type:'success',text:'Your message has been sent privately to Lawson. Thank you!'});setBody('');setTitle('');setName('');}catch(e){setStatus({type:'error',text:e instanceof Error?e.message:'Your message could not be sent. Your text is still here.'});}finally{setSending(false);}}
 return <form className="message-form" onSubmit={submit}><label className="message-field">Subject<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} required placeholder="What’s on your mind?"/></label><label className="message-field">Your name (optional)<input value={name} onChange={e=>setName(e.target.value)} maxLength={80} autoComplete="name" placeholder="Anonymous is fine, too."/></label><div className="contact-trap" aria-hidden="true"><label>Website<input value={trap} onChange={e=>setTrap(e.target.value)} tabIndex={-1} autoComplete="off"/></label></div><div className="message-editor"><div className="editor-toolbar"><button type="button" disabled={preview} onClick={()=>insert('**','**')} aria-label="Insert bold text"><strong>B</strong></button><button type="button" disabled={preview} onClick={()=>insert('*','*')} aria-label="Insert italic text"><em>I</em></button><button type="button" disabled={preview} onClick={()=>insert('\n## ')} aria-label="Insert heading">H2</button><button type="button" disabled={preview} onClick={()=>insert('`','`')} aria-label="Insert inline code">Code</button><button type="button" disabled={preview} onClick={()=>insert('\n- ')} aria-label="Insert list item">List</button><div className="editor-tabs" aria-label="Editor mode"><button type="button" aria-pressed={!preview} onClick={()=>setPreview(false)}>Write</button><button type="button" aria-pressed={preview} onClick={()=>setPreview(true)}>Preview</button></div></div>{preview?<div className="markdown-preview"><ReactMarkdown skipHtml components={{img:()=>null,a:props=><a href={props.href} target="_blank" rel="noopener noreferrer">{props.children}</a>}}>{body||'*Your Markdown preview will appear here.*'}</ReactMarkdown></div>:<textarea ref={editor} aria-label="Message in Markdown" placeholder={'Write a message in Markdown…\n\n## An idea\nA question, a suggestion, or just a hello.'} value={body} onChange={e=>setBody(e.target.value)} maxLength={limit}/>}<div className="editor-bottom"><span>MARKDOWN SUPPORTED</span><span>{body.length.toLocaleString()} / {limit.toLocaleString()}</span></div></div><button className="send-message" disabled={sending||!body.trim()||!title.trim()}>{sending?'Sending…':'Send private message'}</button>{status&&<p role={status.type==='error'?'alert':'status'} className={`message-status ${status.type}`}>{status.text}</p>}</form>;
}
