'use client';
import {useEffect,useRef,useState} from 'react';
import {Guitar,MicVocal,Drum,Music2} from 'lucide-react';
const notes=[{name:'E',frequency:164.81},{name:'A',frequency:220},{name:'D',frequency:293.66},{name:'G',frequency:392},{name:'B',frequency:493.88}];
export function MusicCorner(){
 const audio=useRef<AudioContext|null>(null);const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const [active,setActive]=useState<number|null>(null);const [muted,setMuted]=useState(false);const [error,setError]=useState('');
 useEffect(()=>()=>{if(timeout.current)clearTimeout(timeout.current);void audio.current?.close();},[]);
 async function pluck(i:number){setActive(i);if(timeout.current)clearTimeout(timeout.current);timeout.current=setTimeout(()=>setActive(null),650);if(muted)return;try{const ctx=audio.current??new AudioContext();audio.current=ctx;if(ctx.state==='suspended')await ctx.resume();const t=ctx.currentTime;const oscillator=ctx.createOscillator();const gain=ctx.createGain();oscillator.type='triangle';oscillator.frequency.value=notes[i].frequency;gain.gain.setValueAtTime(.0001,t);gain.gain.exponentialRampToValueAtTime(.12,t+.015);gain.gain.exponentialRampToValueAtTime(.0001,t+.8);oscillator.connect(gain).connect(ctx.destination);oscillator.start(t);oscillator.stop(t+.85);setError('');}catch{setError('Audio is unavailable in this browser.');}}
 return <section className="music-corner" aria-label="Girl band rehearsal corner"><div className="music-corner-label"><span className="eyebrow">REHEARSAL CORNER</span><p>One note before the next idea.</p><div className="band-instruments" aria-label="Guitar, vocals and drums"><span><Guitar size={17}/> GUITAR</span><span><MicVocal size={17}/> VOCALS</span><span><Drum size={17}/> DRUMS</span></div></div><div className="guitar-notes"><div className="guitar-notes-heading"><span><Music2 size={15}/> Tap a string</span><button type="button" onClick={()=>setMuted(v=>!v)} aria-pressed={muted}>{muted?'Sound off':'Sound on'}</button></div><div className="string-buttons">{notes.map((note,i)=><button type="button" key={note.name} onClick={()=>void pluck(i)} className={active===i?'plucked':''} aria-label={`Play ${note.name} guitar note`}><span>{note.name}</span><i aria-hidden="true"/></button>)}</div>{error&&<p role="status" className="music-error">{error}</p>}</div></section>;
}
