export type ResidentLine = { speaker: 'Astra' | 'Nemi'; text: string };
export const scenes: Record<string, [string,string][]> = {
 home: [["Another visitor. Let's see what catches their attention.","Physics, tiny minds, or the slightly noisy corner?"],["We share a website. Not necessarily a conclusion.","Good. Agreeing all the time sounds exhausting."],["There is no need to explain everything immediately.","Finally, a theorem about taking a break."]],
 research: [["A representation is a vector. Its geometry is the interesting part.","So we're watching a network rearrange its little universe?"],["CKA centers features to compare internal geometry rather than absolute position.","Same constellation, different place in the sky. I like that."],["A larger Fisher ratio need not mean absolute within-class compression.","The classes can spread out while separating even more."],["Local label entropy depends on which neighbors we choose.","A boundary can look very different when you zoom out."]],
 linear: [["Ax = b asks whether b belongs to the column space.","And the two equations ask whether their solution sets meet."],["Row operations preserve the solution set.","The equations change outfits. The answers stay."],["A zero coefficient row needs careful interpretation.","Sometimes no line at all means every point. Sometimes none."],["We should check the rank before declaring a unique solution.","Fine. No guessing from a pretty picture."]],
 physics: [["A model needs assumptions before it needs equations.","But imagining the strange possibilities is the fun part."],["Units are a surprisingly effective debugging tool.","Dimensional analysis: the quiet friend who catches everything."]],
 coding: [["Equal values do not imply identical Python objects.","Two matching notebooks can still be two notebooks."],["An experiment should keep its configuration explicit.","Future us deserves more than a mysterious magic number."]],
 lost: [["This corner is allowed to have no research agenda.","Great. I'm assigning us a listening break."],["Silence is also a valid conversational turn.","... I was going to say that."]],
 other: [["Let's check the assumptions.","And then try one slightly weird idea."],["Interesting. We can make this more precise.","But first: what does it mean intuitively?"]],
 consistent: [["The current system is consistent. At least one solution exists.","The target is inside the column space. The equations agree."],["Consistency does not guarantee uniqueness.","Right. They might meet once, or share infinitely many answers."]],
 inconsistent: [["The current system is inconsistent. No exact solution exists.","The target escaped the column space. The equations disagree."]],
};
export function topicFor(path: string) {return path.includes('linear-algebra')?'linear':path.includes('research')?'research':path.includes('physics')?'physics':path.includes('coding')?'coding':path.includes('lost')?'lost':path==='/'?'home':'other';}
