import Link from "next/link";
export const metadata = { title: "Python Foundation" };
export default function PythonFoundation() { return <main className="section shell"><Link className="text-link" href="/coding">Coding and AI Engineering</Link>      <article className="project" id="coding-ai-engineering" style={{scrollMarginTop: '95px'}} aria-labelledby="coding-title">
        <div className="project-head"><span className="project-number">03</span><div><p className="eyebrow">PYTHON × AI</p><h3 id="coding-title">Python<br/>Foundation</h3></div></div>
        <div className="project-body"><p className="project-lead">Strings, numbers, logic, and the objects behind Python names.</p><p style={{color: 'var(--muted)', lineHeight: 1.8, gridColumn: '1 / -1'}}>COGS 18 / Python field notes. Small examples from my first steps in programming.</p>
        <details className="project-detail coding-note" open><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>STRINGS / QUOTES & ESCAPES</summary><p>Outer quotes delimit a string; they are not part of its value. Switch quote styles or escape an inner quote.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"message = \"what's your name?\"\nother = 'what\\'s your name?'\nprint(message)  # what's your name?\nquoted = \"'hello'\"  # inner quotes are content"}</code></pre></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>NUMBERS / DIVISION & MIXED TYPES</summary><p>For built-in int and float values, / returns a float. Mixed int–float arithmetic produces a float. // floors the quotient; two integer operands give an integer result.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"5 / 5          # 1.0\n123 + 5 / 5    # 124.0\n123 + 5 // 5   # 124\n10 + 10.1      # 20.1\n-7 // 2        # -4 (floor, not truncation)"}</code></pre><p>Floating-point numbers have finite precision; very large integers may lose precision when converted to float.</p></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>COMPARISON / ASSIGNMENT & EQUALITY</summary><p>Use = to bind a name and == to compare values. Python has no === operator.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"x = 4\nx == 4             # True\nx != 4             # False\n(6 < 20) and (4 == 4)  # True\n# Other comparisons: <, >, <=, >= "}</code></pre></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>LOGIC / AND, OR & NOT</summary><p>With boolean operands, and requires both to be true; or requires at least one. not negates one expression and goes before it.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"True and False   # False\nTrue or False    # True\nnot True         # False\nnot False        # True\nTrue != False    # True\n# True not False is invalid syntax"}</code></pre></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>OBJECTS / IDENTITY & SHARED REFERENCES</summary><p>Assignment binds a name to an object; it does not copy that object. == compares values; is compares object identity. Two names can refer to the same mutable list.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"a = [1, 2, 3]\nb = a\nc = [1, 2, 3]\na is b    # True\nc is a    # False\nc == a    # True\nb.append(4)\nprint(a)  # [1, 2, 3, 4]\n# id(a) == id(b); id(a) != id(c)"}</code></pre><p>Rebinding <code>b</code> to another object does not change <code>a</code>. Use <code>is</code> for identity checks such as <code>x is None</code>, and <code>==</code> for numeric or string equality. Equal numbers or strings may be reused internally; do not rely on that identity.</p></details>
        <details className="project-detail coding-note"><summary style={{cursor: 'pointer', color: 'var(--accent)', fontFamily: 'ui-monospace, monospace', fontSize: '0.875rem', padding: '12px 0'}}>STRINGS / MEMBERSHIP & EMPTY STRINGS</summary><p>For strings, in tests for a contiguous substring. A space has length 1; the empty string has length 0 and is a substring of every string.</p><pre style={{whiteSpace: 'pre-wrap', overflowWrap: 'anywhere', background: 'var(--blue-wash)', padding: '16px', fontSize: '0.875rem', lineHeight: 1.7, border: '1px solid var(--rule)', marginTop: '16px'}}><code>{"x = 'I love COGS18!'\n'l' in x       # True\n'COGS' in x    # True\n'CSOG' in x    # False\n' ' in x       # True\n'' in x        # True\nlen(' ')       # 1\nlen('')        # 0\n'' in ''       # True"}</code></pre></details>
        </div>
      </article>
</main>; }