import Link from 'next/link';
import {notFound} from 'next/navigation';
import {contextBase,lessons,sourceCommit} from '@/lib/context-lessons';
import {ContextNotes} from '@/components/context-notes';
import {ContextLab} from '@/components/context-labs';
import {ContextChapterNav} from '@/components/context-chapter-nav';
import {ContextIllustration} from '@/components/context-illustrations';
import {ContextQuiz} from '@/components/context-quiz';
export function generateStaticParams(){return lessons.map(l=>({chapter:l.slug}));}
export async function generateMetadata({params}:{params:Promise<{chapter:string}>}){const {chapter}=await params;const l=lessons.find(l=>l.slug===chapter);return {title:l?`${l.title} — Context Harness`:'Chapter not found'};}
export default async function Chapter({params}:{params:Promise<{chapter:string}>}){
 const {chapter}=await params;const index=lessons.findIndex(l=>l.slug===chapter);if(index<0)notFound();const lesson=lessons[index];
 const files=lesson.slug==='incremental-fold'?['src/decompress-shared.ts','src/compress-tool.ts','src/acp-status.ts']:lesson.slug==='compression-doctrine'||lesson.slug==='growth-gate'?['src/config.ts','src/session.ts','src/compress-tool.ts']:index===0?['README.md','reference/architecture.md','src/decompress-shared.ts']:['paper/model-driven-incremental-hierarchical-compression-training-free-multi-generational-context-management-for-long-lived-coding-agents.md','src/compress-tool.ts'];
 return <main className="shell ch-page ch-lesson"><p className="ch-crumb"><Link href="/coding">Coding</Link> / <Link href="/coding/ai-engineering">AI Engineering</Link> / <Link href="/coding/ai-engineering/context-harness">Context Harness</Link> / <Link href={contextBase}>billion-context</Link></p><ContextChapterNav active={index} items={lessons.map(l=>({title:l.title.replace(/^\d+\.\s*/,''),href:`${contextBase}/${l.slug}`}))}/><header className="ch-lesson-header"><p className="ch-kicker">{index===0?'READING MAP':`CHAPTER ${String(index).padStart(2,'0')} / 10`} · CONTEXT HARNESS</p><h1>{lesson.title.replace(/^\d+\.\s*/,'')}</h1><p className="ch-subtitle">{lesson.subtitle}</p><p className="ch-lead">{lesson.intro}</p></header><ContextIllustration slug={lesson.slug}/><ContextLab chapter={lesson.labId} number={index}/><aside className="ch-clarification"><p className="ch-kicker">SOURCE CHECK / CONCEPTUAL BOUNDARY</p><p>{lesson.clarification}</p></aside><section className="ch-note-section"><div className="ch-note-heading"><p className="ch-kicker">THE NOTEBOOK</p><span>Original chapter notes · formulas typeset</span></div><ContextNotes text={lesson.notes}/></section><ContextQuiz quiz={lesson.quiz}/><section className="ch-source"><p className="ch-kicker">FOLLOW THE SOURCE</p><p>Reviewed source: <code>billion-context 0.1.180 / f2b1802</code>. The notes are Lawson’s learning interpretation; the boundary above reflects the reviewed repository.</p>{files.map(file=><a key={file} href={`https://github.com/ranxianglei/billion-context/blob/${sourceCommit}/${file}`} target="_blank" rel="noreferrer">{file.startsWith('paper/')?'Living preprint · architecture and doctrine':file} ↗</a>)}</section><footer className="ch-pagination">{index>0?<Link href={`${contextBase}/${lessons[index-1].slug}`}><small>← PREVIOUS</small>{lessons[index-1].title.replace(/^\d+\.\s*/,'')}</Link>:<Link href={contextBase}>← Notebook overview</Link>}{index<lessons.length-1?<Link href={`${contextBase}/${lessons[index+1].slug}`}><small>NEXT →</small>{lessons[index+1].title.replace(/^\d+\.\s*/,'')}</Link>:<Link href={contextBase}>Return to notebook →</Link>}</footer></main>
}
