import { MathTex } from '@/components/math';
import Link from 'next/link';
import { GeometricDynamics } from '@/components/geometric-dynamics';
import { RepresentationSpace } from '@/components/diagrams';
import { LearningLandscape } from '@/components/learning-landscape';

export const metadata = { title: "Research" };
export default function Research() {return <main>    <section className="section shell research" id="research" aria-labelledby="research-title"><div className="section-top"><span className="section-index">01 / RESEARCH</span><span>SELF-DIRECTED EXPLORATIONS</span></div><div className="section-heading"><h2 id="research-title">Working questions,<br/><em>ongoing experiments.</em></h2><p>Exploratory work on representations and learning dynamics, alongside notes on coding and AI engineering.</p></div>
      <article className="project"><div className="project-head"><span className="project-number">01</span><div><p className="eyebrow">COGNITIVE SCIENCE × AI</p><h3>Representation<br/>Analysis</h3></div><RepresentationSpace/></div><div className="project-body"><p className="project-lead">Exploring the structure of neural representations and their relationship to human cognition.</p><div className="representation-explainer"><div><span className="explainer-label">A SMALL PRIMER / 01</span><h4>What is a representation?</h4><p>In a deep neural network, a representation is an internal vector learned for an input at a hidden layer. The network maps raw data, such as pixels or words, into features that can carry more useful structure for a task. A layer’s activation, an embedding, and a hidden state are all examples.</p><MathTex display tex={String.raw`h^{(0)}=x,\qquad h^{(\ell)}=\sigma\!\left(W^{(\ell)}h^{(\ell-1)}+b^{(\ell)}\right)`} /></div><div><span className="explainer-label">A SMALL PRIMER / 02</span><h4>And its space?</h4><p>For a chosen layer, mapping many inputs through the network gives a collection of representation vectors. Their distances, directions, and similarities form the geometry we call a representation space. Each input becomes a point in that space.</p><MathTex display tex={String.raw`\mathcal H_\ell=\{h^{(\ell)}(x;\theta)\mid x\in\mathcal X\}\subseteq\mathbb R^{d_\ell}`} /><MathTex display tex={String.raw`f_\theta:\mathcal X\to\mathcal H_\ell`} /></div></div><div className="project-detail"><span>01.A / MODEL–BRAIN CORRESPONDENCE</span><p>Representational Similarity Analysis across ResNet-18, ResNet-50, and ResNet-152, compared with early visual cortex (EVC) and inferotemporal cortex (IT). Do stages of artificial visual processing correspond to stages of biological vision?</p><a className="text-link subtopic-link" href="https://github.com/Lawson-Dong/representation-alignment-/tree/resnet-human-visual-cortex-rsa" target="_blank" rel="noopener noreferrer" aria-label="View model–brain correspondence on GitHub">View on GitHub <span aria-hidden="true">↗</span></a></div><div className="project-detail"><span>01.B / SEMANTIC COMPOSITION</span><p>Using hybrid concepts in CLIP, such as a dog body with a cat head, to ask how component concepts combine and transform inside a learned representation space.</p><a className="text-link subtopic-link" href="https://github.com/Lawson-Dong/representation-alignment-/tree/clip-semantic-composition" target="_blank" rel="noopener noreferrer" aria-label="View semantic composition on GitHub">View on GitHub <span aria-hidden="true">↗</span></a></div><GeometricDynamics/></div></article>
      <article className="project"><div className="project-head"><span className="project-number">02</span><div><p className="eyebrow">PHYSICS × DEEP LEARNING</p><h3>Learning<br/>Mechanics</h3></div><LearningLandscape/></div><div className="project-body"><p className="project-lead">What if neural-network training can be studied as a discrete dynamical system?</p><div className="project-detail"><span>02.A / TRAJECTORIES</span><p>Exploring optimizer trajectories under SGD, momentum SGD, and Adam, with discrete velocity and acceleration in parameter space.</p></div><div className="project-detail"><span>02.B / TRAINING DYNAMICS</span><p>Investigating learning-rate schedules, overfitting, a proposed “learning Reynolds number,” and experiments with GPT-2 Small, Medium, and Large. These are exploratory questions, not established results.</p></div><a className="text-link" href="https://github.com/Lawson-Dong/learning-mechanics" target="_blank" rel="noopener noreferrer">View research <span aria-hidden="true">↗</span></a></div></article>
</section><footer className="shell portal-footer"><span>RELATED NOTES</span><Link href="/mathematics/linear-algebra">Mathematics / Linear Algebra</Link></footer></main>;}